version: '3'
services:

  djangoapp:
    build: .
    networks:
      - salesmanagementDB_network
      - nginx_network
    depends_on:
      - database1 
    env_file:
      - config/vars.env
    volumes: 
      - static_volume:${DJANGOSTATICROOT}
      - media_volume:${DJANGOMEDIAROOT}
    restart: always
   
  nginx:
    image: nginx:1.15.8
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:${DJANGOSTATICROOT}
      - media_volume:${DJANGOMEDIAROOT}
    depends_on: 
      - djangoapp
    networks:
      - nginx_network
    restart: always

  database1:
    image: postgres
    env_file:
        - config/vars.env
    networks:
        - salesmanagementDB_network
    volumes:
        - salesmanagementDB_volume:/var/lib/postgresql/data
    restart: always

networks:
  nginx_network:
    driver: bridge
  salesmanagementDB_network:
    driver: bridge
volumes:
  salesmanagementDB_volume:
  static_volume: 
  media_volume:  
